const picker=document.querySelector('#pack'),modelPicker=document.querySelector('#model'),imagePicker=document.querySelector('#image'),runButton=document.querySelector('#run'),status=document.querySelector('#status'),results=document.querySelector('#results'),preview=document.querySelector('#preview'),summary=document.querySelector('#summary');
const REQUIRED_RUNTIME=['ort.wasm.bundle.min.mjs','ort-wasm-simd-threaded.wasm'];
const SCORE_THRESHOLD=.20,IOU_THRESHOLD=.20,MINIMUM_BOX_SIZE=32,INPUT_SIZE=640;
let session,ort;
const say=text=>status.textContent=text;
const clip=(value,minimum,maximum)=>Math.max(minimum,Math.min(maximum,value));
function overlap(a,b){const left=Math.max(a.x,b.x),top=Math.max(a.y,b.y),right=Math.min(a.x+a.width,b.x+b.width),bottom=Math.min(a.y+a.height,b.y+b.height);const intersection=Math.max(0,right-left)*Math.max(0,bottom-top);return intersection/(a.width*a.height+b.width*b.height-intersection||1)}
function suppress(candidates){const retained=[];for(const candidate of candidates.sort((a,b)=>b.score-a.score)){if(retained.every(kept=>overlap(candidate,kept)<IOU_THRESHOLD))retained.push(candidate)}return retained}
function decode(output,scale,padX,padY,imageWidth,imageHeight){const stride=8400,candidates=[];let rawMaximum=0;for(let index=0;index<stride;index++){const score=output[4*stride+index];rawMaximum=Math.max(rawMaximum,score);const width=output[2*stride+index],height=output[3*stride+index];if(score<SCORE_THRESHOLD||Math.sqrt(width*height)<MINIMUM_BOX_SIZE)continue;const x=output[index]-width/2,y=output[stride+index]-height/2;candidates.push({score,x:(x-padX)/scale,y:(y-padY)/scale,width:width/scale,height:height/scale})}return{rawMaximum,boxes:suppress(candidates).map(box=>({score:box.score,x:clip(box.x,0,imageWidth),y:clip(box.y,0,imageHeight),width:clip(box.width,0,imageWidth),height:clip(box.height,0,imageHeight)}))}}
async function loadPack(){const files=new Map([...picker.files].map(file=>[file.name,file]));const modelFile=modelPicker.value;const missing=[...REQUIRED_RUNTIME,modelFile].filter(name=>!files.has(name));if(missing.length){say(`Missing required AI-pack file(s): ${missing.join(', ')}.`);return}try{say('Reading the selected local AI pack…');const urls=[];const blobUrl=file=>{const url=URL.createObjectURL(file);urls.push(url);return url};ort=await import(blobUrl(files.get('ort.wasm.bundle.min.mjs')));ort.env.wasm.numThreads=1;ort.env.wasm.proxy=false;ort.env.wasm.wasmPaths={wasm:blobUrl(files.get('ort-wasm-simd-threaded.wasm'))};session=await ort.InferenceSession.create(new Uint8Array(await files.get(modelFile).arrayBuffer()),{executionProviders:['wasm']});imagePicker.disabled=false;modelPicker.disabled=true;say(`${modelPicker.options[modelPicker.selectedIndex].text} AI pack ready. Choose one test image.`)}catch(error){say(`AI pack failed to load: ${error instanceof Error?error.message:String(error)}`)}}
function setInput(image,scale,padX,padY,width,height){const canvas=document.createElement('canvas');canvas.width=canvas.height=INPUT_SIZE;const context=canvas.getContext('2d',{willReadFrequently:true});context.fillStyle='rgb(114,114,114)';context.fillRect(0,0,INPUT_SIZE,INPUT_SIZE);context.drawImage(image,padX,padY,width,height);const pixels=context.getImageData(0,0,INPUT_SIZE,INPUT_SIZE).data,input=new Float32Array(3*INPUT_SIZE*INPUT_SIZE);for(let index=0;index<INPUT_SIZE*INPUT_SIZE;index++){input[index]=pixels[index*4]/255;input[index+409600]=pixels[index*4+1]/255;input[index+819200]=pixels[index*4+2]/255}return input}
async function runImage(){if(!session||!imagePicker.files[0])return say('Choose an AI pack and a test image first.');try{runButton.disabled=true;say('Preparing image…');const image=await createImageBitmap(imagePicker.files[0]);const scale=Math.min(INPUT_SIZE/image.width,INPUT_SIZE/image.height),width=Math.round(image.width*scale),height=Math.round(image.height*scale),padX=Math.round((INPUT_SIZE-width)/2),padY=Math.round((INPUT_SIZE-height)/2);preview.width=image.width;preview.height=image.height;const display=preview.getContext('2d');display.drawImage(image,0,0);const input=setInput(image,scale,padX,padY,width,height);const start=performance.now();say('Looking for possible insects locally…');const output=await session.run({images:new ort.Tensor('float32',input,[1,3,INPUT_SIZE,INPUT_SIZE])});const inferenceMs=performance.now()-start;const decoded=decode(output.output0.data,scale,padX,padY,image.width,image.height);for(const box of decoded.boxes){display.strokeStyle='#f32b63';display.lineWidth=Math.max(3,image.width/180);display.strokeRect(box.x,box.y,box.width,box.height);display.fillStyle='#f32b63';display.font=`${Math.max(16,image.width/30)}px system-ui`;display.fillText(`${(box.score*100).toFixed(0)}% possible insect`,box.x+4,Math.max(22,box.y-5))}image.close();results.hidden=false;summary.textContent=`${decoded.boxes.length} provisional possible-insect box(es). Highest raw score: ${decoded.rawMaximum.toFixed(4)}. Single-image inference: ${(inferenceMs/1000).toFixed(2)} seconds.`;say('SUCCESS: local inference and provisional box post-processing completed.')}catch(error){say(`Image test failed: ${error instanceof Error?error.message:String(error)}`)}finally{runButton.disabled=false}}
modelPicker.addEventListener('change',()=>{session=undefined;imagePicker.disabled=true;runButton.disabled=true;say('Choose the AI pack folder again after changing model.');});picker.addEventListener('change',loadPack);imagePicker.addEventListener('change',()=>runButton.disabled=!session||!imagePicker.files[0]);runButton.addEventListener('click',runImage);