[platformio]
default_envs = xiao_esp32s3

[env:xiao_esp32s3]
platform = espressif32 @ 7.0.1
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions.csv
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DINSECT_LOGGER_SCHEMA_VERSION=1
    -DINSECT_LOGGER_FIRMWARE_VERSION=\"0.1.0-dev\"
check_tool = cppcheck
check_flags = cppcheck: --std=c++17
